### ISSUE TITLE
GluKey crashing on Start up

### ISSUE THREAD

**Issue by zymurgeeze86** [jpegjames/glukey#2] opened 2018-03-19 15:34 UTC
GluKey was working fine over the weekend, but today crashes on startup and is unusable.  Uninstalled the app, then reinstalled it from the App Store on my 2015 MacBook Pro running macOS Sierra and the app continued to crash instantly.

Please advise.  Thanks!

-Andrew

**Comment by jpegjames** [comment] 2018-03-19 16:26
@zymurgeeze86. Thanks for the info. I'm running High Sierra but will track down a Mac running Sierra. If you want, try this to see if it works:

- If Glukey is not running (which it seems it won't be for you)
- Open Keychain Access from Finder's Utility folder (you can click Go -> Utilities from the Finder menu)
- Search for the Glukey Password and then delete it.
- If Glukey opens, you will have to re-enter your Dexcom password in the settings page.

---

Also, for the sake of trying to debug it, did you happen to start a new sensor between when it was working and when it wasn't? That shouldn't cause a problem, but might help track down the issue.

**Comment by zymurgeeze86** [comment] 2018-03-20 18:56
Hi James,

Thanks for helping out.  While deleting the Glukey Password from my Keychain allowed the program to open, as soon as I put in my username and password and clicked save, the program force quit again.

And I do appreciate your fervor to debug, but alas I did not.  My current sensor had been in for 4 or 5 days when this started, but I am starting a new one tonight, so maybe that’ll help?

Thanks again!





Cheers,
Andrew

Andrew B. Doll
Manager of Programs and Membership
United Nations Association of the National Capital Area
MA, International Relations ‘12
University of Kent Brussels School of International Studies
BA, Politics & Government ‘09
Ohio Wesleyan University
216-470-2686 <tel:216-470-2686>

**Comment by jpegjames** [comment] 2018-03-20 19:46
In Apple's crash reporting, I believe I have found where the error is coming from and your information about it crashing after re-entering the password was very helpful. I will try to figure out the root cause of this issue. It seems that the error is happening while attempting to get data from Dexcom.

The new sensor shouldn't make a difference, but let me know. 

I have a few other questions if you don't mind (feel free to message me via email if you prefer):
* Are you currently in the US?
* Do you use a VPN for your internet connection (if you don't know, it would be typically unlikely but given your signature, your job title I could see it going either way)?

The reason I ask is that there is a non-US Dexcom URL for accessing their API.

**Comment by jpegjames** [comment] 2018-07-10 04:27
I'm closing this one because I the latest release fixed all known issues and I have no reason to conclude at this time that this bug was something different.

**Comment by antonsten** [comment] 2021-12-08 10:41
Bumping this up again as I'm experiencing the same issues. I'm in Sweden, not using a VPN. 

I can open the app and add my dexcom credentials but as soon as I save, the app crashes.

**Comment by jpegjames** [comment] 2021-12-08 14:34
Hi @antonsten: Can you tell me which version of macOS you are running? Has it worked in the past and just recently started crashing?

**Comment by antonsten** [comment] 2021-12-08 15:49
Hey, I am on Monterey. It hasn't worked in the past, I just found out about it today because Glucogram (similar app) that I've been using is having the exact same behavior now (sign in works but then crashes). Wondering if there's a change in data-sharing in the EU?

**Comment by jpegjames** [comment] 2021-12-09 15:39
As of this morning, mine started crashing too. It appears that Dexcom may have changed something and I'm looking into it. At least it will be easier to diagnose now that I'm seeing the same issue.

**Comment by antonsten** [comment] 2021-12-09 15:44
I'm sorry to hear you're experiencing the same issues but also a bit happy because it'll hopefully speed up the fix 👍

**Comment by gkearney** [comment] 2021-12-09 17:22
I see this issue as well. I am running MacOS 12.0 21A5506j I tried deleting the password to no effect. This just started yesterday for me. I am can provide a system information file from my computer, and a sysdiagnose file as well, but it is very large and this system will not let me include it.

**Comment by jpegjames** [comment] 2021-12-09 20:28
Hi @gkearney: No need to provide that info. It's happening to many users (all?) and is not an isolated issue. I hope to have a fix soon.

**Comment by CSpireRJones** [comment] 2021-12-19 15:26
@jpegjames I think I solved the crash on startup issue. It looks like Dexcom changed the spec on the API you were using. I made the required changes and pushed them up to https://github.com/CSpireRJones/glu-key-mirror.git. Please feel free to incorporate the changes if they are helpful.

**Comment by bburgbcross** [comment] 2022-01-10 19:32
@jpegjames Any thoughts on when you may be able to get a fix out for the crash on startup? Thanks for your work on this!

**Comment by antonsten** [comment] 2022-01-10 19:33
@jpegjames Maybe this helps but Glucogram is working again after having the same issue.

**Comment by CSpireRJones** [comment] 2022-01-10 19:57
The code I submitted works. I have been running it for a few weeks now on my machine. I just don't have the ability to release it.

**Comment by gkearney** [comment] 2022-01-10 20:18
I'll just mention that the program GlucoGram appears to offer the sam functionality, with some additions (speech) and continues to work.

https://apps.apple.com/us/app/glucogram/id1107429772?mt=12

Greg

**Comment by jpegjames** [comment] 2022-01-11 22:31
Hi all, 

I'm sorry for the delay—I was unavailable for the past month. Thanks @CSpireRJones for the fix (and updating the Swift code—that was unexpected and much appreciated 🎉). Then my development machine had some issues (fun start for the New Year). 

It appears to be working on my end. I'm going to test it on my other device and then submit it to the App Store tonight.

Thanks @antonsten for mentioning that Glucogram had the same issue.

One day I would like to switch to Dexcom's official API (which came out after this project) so this type of thing doesn't happen, but I'm not sure if that will have the customary 3-hour delay that some other official integrations have. 

I will update and close the issue when the App Store releases the update.

**Comment by jpegjames** [comment] 2022-01-12 14:26
Hi all,

The fixed version is now available on the App Store. Thanks again @CSpireRJones.

**Closed as completed by jpegjames** 2022-01-12 14:26 UTC
